# Generated by Django 5.1 on 2024-08-31 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_category_product_category_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='Cat_name',
            new_name='cat_name',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='Category_name',
            new_name='category',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='order_id',
        ),
        migrations.AddField(
            model_name='order',
            name='order_id',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='products',
            field=models.ManyToManyField(to='products.product'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
